#############################################################################
# Makefile for building: bin/tin_serwer
# Generated by qmake (2.01a) (Qt 4.8.7) on: wt. maj 22 16:16:13 2018
# Project:  tin_serwer.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile tin_serwer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I../../../../boost/boost_1_67_0 -Ibin/moc -Ibin/ui
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lboost_system -lboost_filesystem -lboost_serialization /usr/local/lib/libopencv_core.so.4.0 /usr/local/lib/libopencv_highgui.so.4.0 /usr/local/lib/libopencv_imgproc.so.4.0 /usr/local/lib/libopencv_imgcodecs.so.4.0 /usr/local/lib/libopencv_videoio.so.4.0 -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = bin/obj/

####### Files

SOURCES       = src/main.cpp \
		src/gui/mainwindow.cpp \
		src/server/Server.cpp \
		src/movie/AudioStream.cpp \
		src/movie/Frame.cpp \
		src/movie/Movie.cpp \
		src/movie/VideoStream.cpp \
		src/network/tcp_connection.cpp \
		src/network/tcp_server.cpp bin/moc/moc_mainwindow.cpp
OBJECTS       = bin/obj/main.o \
		bin/obj/mainwindow.o \
		bin/obj/Server.o \
		bin/obj/AudioStream.o \
		bin/obj/Frame.o \
		bin/obj/Movie.o \
		bin/obj/VideoStream.o \
		bin/obj/tcp_connection.o \
		bin/obj/tcp_server.o \
		bin/obj/moc_mainwindow.o
DIST          = bin \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		tin_serwer.pro
QMAKE_TARGET  = tin_serwer
DESTDIR       = bin/
TARGET        = bin/tin_serwer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): bin/ui/ui_mainwindow.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tin_serwer.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile tin_serwer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile tin_serwer.pro

dist: 
	@$(CHK_DIR_EXISTS) bin/obj/tin_serwer1.0.0 || $(MKDIR) bin/obj/tin_serwer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) bin/obj/tin_serwer1.0.0/ && $(COPY_FILE) --parents src/gui/mainwindow.h src/server/Server.hpp src/movie/AudioStream.hpp src/movie/Frame.hpp src/movie/Movie.hpp src/movie/Resolution.hpp src/movie/VideoStream.hpp src/network/tcp_connection.hpp src/network/tcp_server.hpp bin/obj/tin_serwer1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/gui/mainwindow.cpp src/server/Server.cpp src/movie/AudioStream.cpp src/movie/Frame.cpp src/movie/Movie.cpp src/movie/VideoStream.cpp src/network/tcp_connection.cpp src/network/tcp_server.cpp bin/obj/tin_serwer1.0.0/ && $(COPY_FILE) --parents src/gui/mainwindow.ui bin/obj/tin_serwer1.0.0/ && (cd `dirname bin/obj/tin_serwer1.0.0` && $(TAR) tin_serwer1.0.0.tar tin_serwer1.0.0 && $(COMPRESS) tin_serwer1.0.0.tar) && $(MOVE) `dirname bin/obj/tin_serwer1.0.0`/tin_serwer1.0.0.tar.gz . && $(DEL_FILE) -r bin/obj/tin_serwer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: bin/moc/moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) bin/moc/moc_mainwindow.cpp
bin/moc/moc_mainwindow.cpp: src/server/Server.hpp \
		src/gui/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/gui/mainwindow.h -o bin/moc/moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: bin/ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) bin/ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: bin/ui/ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) bin/ui/ui_mainwindow.h
bin/ui/ui_mainwindow.h: src/gui/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt4/bin/uic src/gui/mainwindow.ui -o bin/ui/ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

bin/obj/main.o: src/main.cpp src/gui/mainwindow.h \
		src/server/Server.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/obj/main.o src/main.cpp

bin/obj/mainwindow.o: src/gui/mainwindow.cpp src/gui/mainwindow.h \
		src/server/Server.hpp \
		bin/ui/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/obj/mainwindow.o src/gui/mainwindow.cpp

bin/obj/Server.o: src/server/Server.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/obj/Server.o src/server/Server.cpp

bin/obj/AudioStream.o: src/movie/AudioStream.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/obj/AudioStream.o src/movie/AudioStream.cpp

bin/obj/Frame.o: src/movie/Frame.cpp src/movie/Frame.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/obj/Frame.o src/movie/Frame.cpp

bin/obj/Movie.o: src/movie/Movie.cpp src/movie/Movie.hpp \
		src/movie/VideoStream.hpp \
		src/movie/Frame.hpp \
		src/movie/AudioStream.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/obj/Movie.o src/movie/Movie.cpp

bin/obj/VideoStream.o: src/movie/VideoStream.cpp src/movie/VideoStream.hpp \
		src/movie/Frame.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/obj/VideoStream.o src/movie/VideoStream.cpp

bin/obj/tcp_connection.o: src/network/tcp_connection.cpp src/network/tcp_connection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/obj/tcp_connection.o src/network/tcp_connection.cpp

bin/obj/tcp_server.o: src/network/tcp_server.cpp src/network/tcp_connection.hpp \
		src/network/tcp_server.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/obj/tcp_server.o src/network/tcp_server.cpp

bin/obj/moc_mainwindow.o: bin/moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bin/obj/moc_mainwindow.o bin/moc/moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

